/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface FileInfo {
  id: string
  path: string
  width: number
  height: number
  channels: number
  bitpix: number
  frameType: string
  exposureTime?: number
  temperature?: number
  gain?: number
  filterName?: string
  bayerPattern?: string
}
export interface DetectedStar {
  x: number
  y: number
  flux: number
  hfr: number
  peak: number
}
export interface HistogramData {
  bins: Array<number>
  min: number
  max: number
  channel: number
}
export interface StretchConfig {
  shadows: number
  midtones: number
  highlights: number
}
export interface StackingConfig {
  method: string
  kappa?: number
  iterations?: number
}
export declare function initLogger(): void
/**
 * Load only the FITS headers for a file (no pixel data loaded into memory).
 * Returns metadata for display in the file list.
 */
export declare function loadFitsFile(path: string): Promise<FileInfo>
/** Remove an image from the store to free memory. */
export declare function releaseImage(id: string): void
/** Release all images from the store. */
export declare function releaseAllImages(): void
/** Get basic info (width, height, channels) for any image in the store. */
export interface ImageInfo {
  width: number
  height: number
  channels: number
}
export declare function getImageInfo(imageId: string): ImageInfo
/** Get a histogram for a specific channel of a stored image. */
export declare function getHistogram(imageId: string, channel: number, bins: number): HistogramData
/** Get auto-stretch parameters for a stored image. */
export declare function getAutoStretch(imageId: string): StretchConfig
/**
 * Get RGBA preview data for an image (for rendering on HTML Canvas).
 * Returns a Buffer of width * height * 4 bytes (RGBA).
 */
export declare function getPreview(imageId: string, stretch?: StretchConfig | undefined | null): Buffer
/**
 * Load a single FITS file fully (headers + pixel data) into the store for preview.
 * Use this when the user clicks on a file to preview it.
 */
export declare function loadPreview(path: string): Promise<string>
/** Save an image to disk in the specified format. */
export declare function saveImage(imageId: string, path: string, format: string, stretch?: StretchConfig | undefined | null): Promise<void>
/**
 * Run the complete pipeline. Takes file paths (not store IDs) and returns
 * the ID of the stacked result stored in the image store.
 *
 * Memory-efficient: the pipeline reads frames from disk one at a time.
 * Only the final result is kept in memory.
 */
export declare function runPipeline(lightPaths: Array<string>, darkPaths: Array<string>, flatPaths: Array<string>, biasPaths: Array<string>, bayerPattern: string | undefined | null, stackingConfig: StackingConfig): Promise<string>
